twilio: # Twilio credentials got by www.twilio.com #
  account_sid:
  auth_token:
  trial_number:
server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:mem:database
    username: sa
  jpa.hibernate:
    ddl-auto: update
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
